<a href="https://colab.research.google.com/github/Roshitatmg/AI-ML/blob/main/Worksheet0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

4 TO - DO - Task

Please complete all the problem listed below.

4.1 Exercise on Functions:

Task - 1:

Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.
• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units(value, conversion_type):
    """
    Convert between units of length, weight, and volume.

    Parameters:
        value (float): The numeric value to convert.
        conversion_type (str): The type of conversion. Options:
            'm_to_ft', 'ft_to_m',
            'kg_to_lbs', 'lbs_to_kg',
            'l_to_gal', 'gal_to_l'

    Returns:
        float: The converted value.
    """
    conversions = {
        "m_to_ft": value * 3.28084,
        "ft_to_m": value / 3.28084,
        "kg_to_lbs": value * 2.20462,
        "lbs_to_kg": value / 2.20462,
        "l_to_gal": value * 0.264172,
        "gal_to_l": value / 0.264172,
    }
    return conversions.get(conversion_type, None)


def main():
    print("Choose conversion type:")
    print("1. Meters to Feet")
    print("2. Feet to Meters")
    print("3. Kilograms to Pounds")
    print("4. Pounds to Kilograms")
    print("5. Liters to Gallons")
    print("6. Gallons to Liters")

    try:
        choice = int(input("Enter choice (1-6): "))
        value = float(input("Enter value to convert: "))

        mapping = {
            1: "m_to_ft",
            2: "ft_to_m",
            3: "kg_to_lbs",
            4: "lbs_to_kg",
            5: "l_to_gal",
            6: "gal_to_l",
        }

        conversion_type = mapping.get(choice)
        if conversion_type:
            result = convert_units(value, conversion_type)
            print(f"Converted value: {result:.2f}")
        else:
            print("Invalid choice. Please select between 1 and 6.")

    except ValueError:
        print("Error: Please enter numeric values only.")


if __name__ == "__main__":
    main()

Choose conversion type:
1. Meters to Feet
2. Feet to Meters
3. Kilograms to Pounds
4. Pounds to Kilograms
5. Liters to Gallons
6. Gallons to Liters
Enter choice (1-6): 4
Enter value to convert: 13.2
Converted value: 5.99


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18

6CS012 Worksheet - 0 Siman Giri

3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The sum of the numbers.
    """
    return sum(numbers)


def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The average of the numbers.
    """
    return sum(numbers) / len(numbers)


def calculate_max(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The maximum value.
    """
    return max(numbers)


def calculate_min(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
        numbers (list): A list of numeric values.

    Returns:
        float: The minimum value.
    """
    return min(numbers)


def main():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = int(input("Enter choice (1-4): "))
        numbers = input("Enter numbers separated by spaces: ").split()
        numbers = [float(num) for num in numbers]


        if not numbers:
            raise ValueError("Empty list provided.")

        operations = {
            1: calculate_sum,
            2: calculate_average,
            3: calculate_max,
            4: calculate_min,
        }

        operation = operations.get(choice)
        if operation:
            result = operation(numbers)
            print(f"Result: {result}")
        else:
            print("Invalid choice. Please select between 1 and 4.")

    except ValueError as e:
        print(f"Error: {e}. Please enter valid numeric values.")


if __name__ == "__main__":
    main()

Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter choice (1-4): 1
Enter numbers separated by spaces: 1 2 3
Result: 6.0


4.2 Exercise on List Manipulation:

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    """
    Extract every other element from a list, starting with the first.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every other element.
    """
    return lst[::2]


numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)
print(result)

[1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    """
    Return a sublist from a given list, starting at 'start' index
    and ending at 'end' index (inclusive).

    Parameters:
        lst (list): The input list.
        start (int): The starting index.
        end (int): The ending index (inclusive).

    Returns:
        list: The sliced sublist.
    """
    return lst[start:end+1]

numbers = [1, 2, 3, 4, 5, 6]
result = get_sublist(numbers, 2, 4)
print(result)

[3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_list(lst):
    """
    Reverse a list using slicing.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list with elements in reverse order.
    """
    return lst[::-1]

numbers = [1, 2, 3, 4, 5]
result = reverse_list(numbers)
print(result)


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    """
    Remove the first and last elements of a list.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list without the first and last elements.
    """
    return lst[1:-1]



numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)
print(result)

[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    """
    Extract the first n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): Number of elements to extract.

    Returns:
        list: A new list containing the first n elements.
    """
    return lst[:n]



numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)
print(result)

[1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
    """
    Extract the last n elements from a list.

    Parameters:
        lst (list): The input list.
        n (int): Number of elements to extract.

    Returns:
        list: A new list containing the last n elements.
    """
    return lst[-n:]



numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)
print(result)

[4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
    """
    Extract elements in reverse order starting from the second-to-last element,
    skipping one element in between.

    Parameters:
        lst (list): The input list.

    Returns:
        list: A new list containing every second element in reverse order.
    """
    return lst[-2::-2]


numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)
print(result)

[5, 3, 1]


4.3 Exercise on Nested List:

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
    """
    Flatten a nested list into a single list.

    Parameters:
        lst (list): A nested list (list of lists).

    Returns:
        list: A flattened version of the list.
    """
    flat_list = []
    for sublist in lst:
        flat_list.extend(sublist)
    return flat_list


nested = [[1, 2], [3, 4], [5]]
result = flatten(nested)
print(result)

[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
    """
    Access a specific element from a nested list given its indices.

    Parameters:
        lst (list): The nested list.
        indices (list): A list of indices representing the path to the element.

    Returns:
        any: The element at the specified position.
    """
    element = lst
    for index in indices:
        element = element[index]
    return element


nested = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
result = access_nested_element(nested, [1, 2])
print(result)

6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    """
    Calculate the sum of all numbers in a nested list (any depth).

    Parameters:
        lst (list): A nested list containing numbers or other lists.

    Returns:
        int/float: The sum of all numeric elements.
    """
    total = 0
    for element in lst:
        if isinstance(element, list):
            total += sum_nested(element)
        else:
            total += element
    return total


nested = [[1, 2], [3, [4, 5]], 6]
result = sum_nested(nested)
print(result)

21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    """
    Remove all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): A nested list (list of lists).
        elem (any): The element to remove.

    Returns:
        list: A new nested list with the element removed.
    """
    result = []
    for sublist in lst:
        if isinstance(sublist, list):
            filtered = [x for x in sublist if x != elem]
            result.append(filtered)
        else:
            if sublist != elem:
                result.append(sublist)
    return result


nested = [[1, 2], [3, 2], [4, 5]]
result = remove_element(nested, 2)
print(result)

[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    """
    Find the maximum element in a nested list (any depth).

    Parameters:
        lst (list): A nested list containing numbers or other lists.

    Returns:
        int/float: The maximum numeric element.
    """
    max_val = float('-inf')
    for element in lst:
        if isinstance(element, list):
            sub_max = find_max(element)
            if sub_max > max_val:
                max_val = sub_max
        else:
            if element > max_val:
                max_val = element
    return max_val


nested = [[1, 2], [3, [4, 5]], 6]
result = find_max(nested)
print(result)

6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
def count_occurrences(lst, elem):
    """
    Count how many times a specific element appears in a nested list.

    Parameters:
        lst (list): A nested list containing elements or other lists.
        elem (any): The element to count.

    Returns:
        int: The number of occurrences of elem in the nested list.
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count


nested = [[1, 2], [2, 3], [2, 4]]
result = count_occurrences(nested, 2)
print(result)

3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
    """
    Flatten a deeply nested list into a single list.

    Parameters:
        lst (list): A nested list of arbitrary depth.

    Returns:
        list: A flattened version of the list.
    """
    flat_list = []
    for element in lst:
        if isinstance(element, list):
            flat_list.extend(deep_flatten(element))
        else:
            flat_list.append(element)
    return flat_list


nested = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested)
print(result)

[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    """
    Calculate the average of all elements in a nested list (any depth).

    Parameters:
        lst (list): A nested list containing numbers or other lists.

    Returns:
        float: The average of all numeric elements.
    """
    def helper(sublist):
        total = 0
        count = 0
        for element in sublist:
            if isinstance(element, list):
                sub_total, sub_count = helper(element)
                total += sub_total
                count += sub_count
            else:
                total += element
                count += 1
        return total, count

    total, count = helper(lst)
    return total / count if count != 0 else 0


nested = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested)
print(result)

3.5


10 To - Do - NumPy

Please complete all the problems listed below:

10.1 Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("Empty 2x2 array:\n", empty_array)

# 2. Initialize an all-one array with size 4x2
ones_array = np.ones((4, 2))
print("\nAll ones 4x2 array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
full_array = np.full((3, 3), 7)  # Example: 3x3 filled with 7
print("\nFull 3x3 array with 7:\n", full_array)

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("\nZeros like given array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("\nOnes like given array:\n", ones_like_array)

# 6. Convert an existing list to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\nConverted numpy array:\n", numpy_array)

Empty 2x2 array:
 [[2.46868522e-315 0.00000000e+000]
 [3.68065907e+180 2.61354254e-306]]

All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

Full 3x3 array with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

Zeros like given array:
 [[0 0 0]
 [0 0 0]]

Ones like given array:
 [[1 1 1]
 [1 1 1]]

Converted numpy array:
 [1 2 3 4]


Problem - 2:

Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr_range = np.arange(10, 50)
print("Array from 10 to 49:\n", arr_range)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n3x3 matrix from 0 to 8:\n", matrix_3x3)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3x3 Identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
print("\nRandom array of size 30:\n", random_array)
print("Mean of array:", random_array.mean())

# 5. Create a 10x10 array with random values and find min and max
random_10x10 = np.random.random((10, 10))
print("\n10x10 random array:\n", random_10x10)
print("Minimum value:", random_10x10.min())
print("Maximum value:", random_10x10.max())

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1   # index 4 is the 5th element
print("\nZero array with 5th element replaced:\n", zero_array)

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\nReversed array:\n", reversed_arr)

# 8. Create a 2D array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n8x8 Checkerboard pattern:\n", checkerboard)

Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Random array of size 30:
 [0.34889667 0.34310329 0.42047258 0.73662918 0.86974935 0.78338915
 0.75026632 0.37173286 0.52218133 0.01490098 0.71500389 0.59186044
 0.50795337 0.07947764 0.41331248 0.75628812 0.78810824 0.19813028
 0.43098674 0.03401494 0.6625252  0.41619895 0.5035103  0.66257241
 0.70974599 0.90907284 0.53292957 0.99113936 0.9579082  0.11596151]
Mean of array: 0.5379340719833059

10x10 random array:
 [[0.50000157 0.92395331 0.40751064 0.96057466 0.99388137 0.69942843
  0.56827666 0.03296612 0.02455689 0.95728911]
 [0.42176859 0.84561135 0.968498   0.75584081 0.26418629 0.3823657
  0.98216244 0.31104219 0.83416152 0.23808131]
 [0.50783419 0.77544331 0.19475289 0.04188999 0.08148149 0.18166503
  0.37561467 0.12442877 0

Problem - 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_xy = x + y
print("Addition of x and y:\n", add_xy)

# 2. Subtract the two arrays
sub_xy = x - y
print("\nSubtraction of x and y:\n", sub_xy)

# 3. Multiply the array with any integer (example: multiply x by 3)
mul_x = x * 3
print("\nMultiplication of x by 3:\n", mul_x)

# 4. Find the square of each element of the array (example: square of y)
square_y = y ** 2
print("\nSquare of each element in y:\n", square_y)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\nDot product v·w:", dot_vw)
print("Dot product x·v:\n", dot_xv)
print("Dot product x·y:\n", dot_xy)

# 6. Concatenate x and y along rows; concatenate v and w along columns
concat_xy = np.concatenate((x, y), axis=0)
concat_vw = np.vstack((v, w))
print("\nConcatenate x and y along rows:\n", concat_xy)
print("Concatenate v and w along columns:\n", concat_vw)

# 7. Concatenate x and v
try:
    concat_xv = np.concatenate((x, v))
    print("\nConcatenate x and v:\n", concat_xv)
except ValueError as e:
    print("\nError when concatenating x and v:", e)

Addition of x and y:
 [[ 6  8]
 [10 13]]

Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

Multiplication of x by 3:
 [[ 3  6]
 [ 9 15]]

Square of each element in y:
 [[25 36]
 [49 64]]

Dot product v·w: 219
Dot product x·v:
 [29 77]
Dot product x·y:
 [[19 22]
 [50 58]]

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w along columns:
 [[ 9 10]
 [11 12]]

Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
import numpy as np

# Given matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A⁻¹ = I
A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)
print("A * A⁻¹:\n", identity)

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\nAB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

# 3. Prove (AB)ᵀ = Bᵀ Aᵀ
AB_T = AB.T
BT_AT = np.dot(B.T, A.T)
print("\n(AB)ᵀ:\n", AB_T)
print("Bᵀ Aᵀ:\n", BT_AT)
print("Are they equal?", np.array_equal(AB_T, BT_AT))

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA equal? False

(AB)ᵀ:
 [[23 51]
 [13 29]]
Bᵀ Aᵀ:
 [[23 51]
 [13 29]]
Are they equal? True


In [ ]:
# Coefficient matrix A and constant vector B
A_eq = np.array([[2, -3, 1],
                 [1, -1, 2],
                 [3,  1, -1]])

B_eq = np.array([-1, -3, 9])

# Solve using inverse method
A_inv_eq = np.linalg.inv(A_eq)
X = np.dot(A_inv_eq, B_eq)
print("\nSolution using inverse method (x, y, z):", X)

# Alternatively, use np.linalg.solve (more stable)
X_solve = np.linalg.solve(A_eq, B_eq)
print("Solution using np.linalg.solve (x, y, z):", X_solve)


Solution using inverse method (x, y, z): [ 2.  1. -2.]
Solution using np.linalg.solve (x, y, z): [ 2.  1. -2.]


10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import numpy as np
import time

# Size of arrays
N = 1_000_000

list1 = list(range(N))
list2 = list(range(N))

start_time = time.time()
list_result = [a + b for a, b in zip(list1, list2)]
end_time = time.time()

print("Python list addition time:", end_time - start_time, "seconds")

arr1 = np.arange(N)
arr2 = np.arange(N)

start_time = time.time()
numpy_result = arr1 + arr2
end_time = time.time()

print("NumPy array addition time:", end_time - start_time, "seconds")

Python list addition time: 0.26231932640075684 seconds
NumPy array addition time: 0.0091094970703125 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import numpy as np
import time

# Size of arrays
N = 1000000

list1 = list(range(N))
list2 = list(range(N))

start_time = time.time()
list_result = [a * b for a, b in zip(list1, list2)]
end_time = time.time()

print("Python list multiplication time:", end_time - start_time, "seconds")

arr1 = np.arange(N)
arr2 = np.arange(N)

start_time = time.time()
numpy_result = arr1 * arr2
end_time = time.time()

print("NumPy array multiplication time:", end_time - start_time, "seconds")

Python list multiplication time: 0.10265755653381348 seconds
NumPy array multiplication time: 0.005306720733642578 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
import numpy as np
import time

N = 1_000_000

list1 = list(range(N))
list2 = list(range(N))

start_time = time.time()
dot_list = sum(a * b for a, b in zip(list1, list2))
end_time = time.time()

print("Python list dot product:", dot_list)
print("Time taken (Python lists):", end_time - start_time, "seconds")

arr1 = np.arange(N)
arr2 = np.arange(N)

start_time = time.time()
dot_numpy = np.dot(arr1, arr2)
end_time = time.time()

print("\nNumPy array dot product:", dot_numpy)
print("Time taken (NumPy arrays):", end_time - start_time, "seconds")

Python list dot product: 333332833333500000
Time taken (Python lists): 0.40662693977355957 seconds

NumPy array dot product: 333332833333500000
Time taken (NumPy arrays): 0.01627182960510254 seconds


4. Matrix Multiplication


• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# Matrix size
N = 1000

# Create two matrices using lists
listA = [[i for i in range(N)] for _ in range(N)]
listB = [[j for j in range(N)] for _ in range(N)]

# Matrix multiplication using nested loops
start_time = time.time()
list_result = [[sum(a * b for a, b in zip(rowA, colB))
                for colB in zip(*listB)]
               for rowA in listA]
end_time = time.time()

print("Python list matrix multiplication time:", end_time - start_time, "seconds")

arrA = np.array(listA)
arrB = np.array(listB)

start_time = time.time()
numpy_result = np.dot(arrA, arrB)
end_time = time.time()

print("NumPy matrix multiplication time:", end_time - start_time, "seconds")

Python list matrix multiplication time: 181.48458409309387 seconds
NumPy matrix multiplication time: 1.3611907958984375 seconds
